import { syncCustomPartAssembly } from './custom-part-assembly';
import { realGeometryThumbnail } from './geometry-thumbnail';
import type { CustomPart, CustomPartType, PlenumPort } from './types';

// Active promotional custom-part families plus retired ids kept only so older saved
// parts (round-reducer / round-elbow / t-piece) still deserialize. Retired ids are
// intentionally absent from PROMOTIONAL_TEMPLATES: those are standard stocked round
// parts an installer buys off the shelf, not job-specific fabricated fittings.
export type PromotionalTemplateId = 'rectangular-transition' | 'rectangular-heitto' | 'rectangular-to-round' | 'rectangular-elbow' | 'round-saddle' | 'rectangular-saddle' | 'closed-box' | 'equipment-adapter' | 'plenum-four-outlet' | 'round-reducer' | 'round-elbow' | 't-piece';
export type TemplateFamily = 'rectangular-loft' | 'mixed-loft' | 'round-loft' | 'elbow' | 'host-branch' | 'plenum';
export type HeroGroup = 'Shape changes' | 'Bends' | 'Boxes' | 'Connections';
export interface TemplatePreset { id: string; name: string; defaults: Partial<CustomPart> }
export interface PromotionalTemplateDefinition {
  id: PromotionalTemplateId; name: string; description: string; group: HeroGroup; category: 'Rectangular' | 'Round' | 'Mixed profile' | 'Branches' | 'Plenums'; family: TemplateFamily;
  profilePath: string; portCount: number; tags: string[]; partType: CustomPartType; defaults: Partial<CustomPart>; presets: TemplatePreset[];
}

const port = (value: Partial<PlenumPort> & Pick<PlenumPort, 'id' | 'name' | 'face' | 'shape'>): PlenumPort => ({ widthMm: 200, heightMm: 160, diameterMm: 160, offsetHorizontalMm: 0, offsetVerticalMm: 0, projectionMm: 100, rotationDeg: 0, role: 'outlet', notes: '', ...value });
const preset = (id: string, name: string, defaults: Partial<CustomPart>): TemplatePreset => ({ id, name, defaults });

const rectTransitionPresets = [
  preset('centred-reducer', 'Centred reducer', { endAWidthMm: 500, endAHeightMm: 300, endBWidthMm: 300, endBHeightMm: 200, horizontalOffsetMm: 0, verticalOffsetMm: 0 }),
  preset('centred-enlargement', 'Centred enlargement', { endAWidthMm: 300, endAHeightMm: 200, endBWidthMm: 500, endBHeightMm: 300, horizontalOffsetMm: 0, verticalOffsetMm: 0 }),
  preset('horizontal-offset', 'Horizontal offset', { horizontalOffsetMm: 140, verticalOffsetMm: 0 }), preset('vertical-offset', 'Vertical offset', { horizontalOffsetMm: 0, verticalOffsetMm: 120 }),
  preset('double-offset', 'Double offset', { horizontalOffsetMm: 120, verticalOffsetMm: 80 }), preset('one-side-fixed', 'One side fixed', { horizontalOffsetMm: -100, verticalOffsetMm: 0 }),
  preset('two-sides-fixed', 'Two sides fixed', { horizontalOffsetMm: -100, verticalOffsetMm: -50 }), preset('four-sided-taper', 'Four-sided taper', { horizontalOffsetMm: 0, verticalOffsetMm: 0, endBWidthMm: 260, endBHeightMm: 160 }),
];
const elbowPresets = (round: boolean) => [preset('radius-90', 'Radius 90°', { bendAngleDeg: 90, bendRadiusMm: round ? 320 : 450, segmentCount: 14 }), preset('radius-45', 'Radius 45°', { bendAngleDeg: 45, bendRadiusMm: round ? 300 : 420, segmentCount: 8 }), preset('segmented-90', 'Segmented 90°', { bendAngleDeg: 90, bendRadiusMm: round ? 280 : 380, segmentCount: 5 }), preset('long-radius', 'Long radius', { bendAngleDeg: 90, bendRadiusMm: round ? 450 : 650, segmentCount: 16 })];

// Host duct main opening (the duct's own open end) shared by every saddle preset.
const hostOutlet = (widthMm: number, heightMm: number): PlenumPort => port({ id: 'P2', name: 'Main outlet P2', face: 'front', shape: 'rectangular', widthMm, heightMm, projectionMm: 60, role: 'outlet' });
const saddlePorts = [hostOutlet(500, 300), port({ id: 'B1', name: 'Round saddle B1', face: 'top', shape: 'round', diameterMm: 200, offsetHorizontalMm: 0, projectionMm: 150, role: 'branch' })];
const rectSaddlePorts = [hostOutlet(600, 400), port({ id: 'B1', name: 'Rectangular saddle B1', face: 'right', shape: 'rectangular', widthMm: 300, heightMm: 200, projectionMm: 160, role: 'branch' })];
const closedBoxPorts = [port({ id: 'B1', name: 'Round connection B1', face: 'front', shape: 'round', diameterMm: 200, offsetHorizontalMm: 0, offsetVerticalMm: 0, projectionMm: 120, role: 'outlet' })];
const plenumPorts = [
  port({ id: 'B1', name: 'Round outlet B1', face: 'front', shape: 'round', diameterMm: 160, offsetHorizontalMm: -170, offsetVerticalMm: -90, projectionMm: 110 }),
  port({ id: 'B2', name: 'Round outlet B2', face: 'front', shape: 'round', diameterMm: 160, offsetHorizontalMm: 170, offsetVerticalMm: -90, projectionMm: 110 }),
  port({ id: 'B3', name: 'Round outlet B3', face: 'front', shape: 'round', diameterMm: 160, offsetHorizontalMm: -170, offsetVerticalMm: 90, projectionMm: 110 }),
  port({ id: 'B4', name: 'Round outlet B4', face: 'front', shape: 'round', diameterMm: 160, offsetHorizontalMm: 170, offsetVerticalMm: 90, projectionMm: 110 }),
];

// The default library focuses on parts whose sizes, offsets or connection
// positions must be specified per job. Standard stocked round parts (round
// straight duct, round bends, concentric round reducers, ordinary round T-pieces,
// standard connectors / end caps) are intentionally excluded — they are catalogue
// purchases, not custom fabrication. Every entry reuses an existing geometry
// generator; no new part-type geometry is introduced here.
export const PROMOTIONAL_TEMPLATES: PromotionalTemplateDefinition[] = [
  // --- SHAPE CHANGES -------------------------------------------------------
  { id: 'rectangular-transition', name: 'Rectangular transition', description: 'Reducers and enlargements between two rectangular sizes (muunto).', group: 'Shape changes', category: 'Rectangular', family: 'rectangular-loft', profilePath: 'Rectangle → Rectangle', portCount: 2, tags: ['transition', 'muunto', 'reducer', 'supistus'], partType: 'rectangular-transition', defaults: { name: '500 × 300 → 300 × 200 muunto', presetId: 'centred-reducer', endAWidthMm: 500, endAHeightMm: 300, endBWidthMm: 300, endBHeightMm: 200, lengthMm: 500, horizontalOffsetMm: 0, verticalOffsetMm: 0 }, presets: rectTransitionPresets },
  { id: 'rectangular-heitto', name: 'Rectangular offset (heitto)', description: 'Moves a rectangular run sideways and up without changing size.', group: 'Shape changes', category: 'Rectangular', family: 'rectangular-loft', profilePath: 'Rectangle ⇢ Rectangle', portCount: 2, tags: ['heitto', 'offset', 'siirtymä', 'jog'], partType: 'rectangular-transition', defaults: { name: '500 × 300 heitto, 200 across / 250 up', presetId: 'double-offset', endAWidthMm: 500, endAHeightMm: 300, endBWidthMm: 500, endBHeightMm: 300, lengthMm: 800, horizontalOffsetMm: 200, verticalOffsetMm: 250 }, presets: [preset('double-offset', 'Sideways and up', { horizontalOffsetMm: 200, verticalOffsetMm: 250 }), preset('horizontal-offset', 'Sideways only', { horizontalOffsetMm: 200, verticalOffsetMm: 0 }), preset('vertical-offset', 'Up only', { horizontalOffsetMm: 0, verticalOffsetMm: 250 })] },
  { id: 'rectangular-to-round', name: 'Rectangular → round', description: 'Rectangular duct to a round spiral duct, kept flush on one side.', group: 'Shape changes', category: 'Mixed profile', family: 'mixed-loft', profilePath: 'Rectangle → Circle', portCount: 2, tags: ['transition', 'muunto', 'mixed', 'round', 'pyöreä'], partType: 'rectangular-to-round-transition', defaults: { name: '500 × 300 → Ø250 eccentric adapter', presetId: 'eccentric', endAWidthMm: 500, endAHeightMm: 300, endBDiameterMm: 250, lengthMm: 500, horizontalOffsetMm: 100, verticalOffsetMm: -25 }, presets: [preset('centred', 'Centred', { horizontalOffsetMm: 0, verticalOffsetMm: 0 }), preset('eccentric', 'Eccentric', { horizontalOffsetMm: 100, verticalOffsetMm: -25 })] },
  // --- BENDS ---------------------------------------------------------------
  { id: 'rectangular-elbow', name: 'Rectangular custom bend', description: 'Swept rectangular bend — width, height, radius, angle and tails all variable.', group: 'Bends', category: 'Rectangular', family: 'elbow', profilePath: 'Rectangle ↱ Rectangle', portCount: 2, tags: ['elbow', 'bend', 'käyrä', 'kulma', 'radius'], partType: 'rectangular-elbow', defaults: { name: '500 × 300 rectangular 90° bend', presetId: 'radius-90', endAWidthMm: 500, endAHeightMm: 300, endBWidthMm: 500, endBHeightMm: 300, bendRadiusMm: 450, bendAngleDeg: 90, inletExtensionMm: 140, outletExtensionMm: 140, segmentCount: 14, lengthMm: 450 }, presets: elbowPresets(false) },
  // --- BOXES ---------------------------------------------------------------
  { id: 'closed-box', name: 'Closed custom box', description: 'Closed rectangular body with one or more positioned connections.', group: 'Boxes', category: 'Plenums', family: 'plenum', profilePath: 'Box + connection', portCount: 2, tags: ['laatikko', 'box', 'kotelo', 'body', 'connection'], partType: 'plenum-box', defaults: { name: '600 × 400 × 350 closed equipment box', presetId: 'one-round', bodyWidthMm: 600, bodyHeightMm: 400, bodyDepthMm: 350, endAWidthMm: 400, endAHeightMm: 250, plenumPorts: closedBoxPorts }, presets: [preset('one-round', 'One round connection', { plenumPorts: closedBoxPorts }), preset('one-rect', 'One rectangular connection', { plenumPorts: [{ ...closedBoxPorts[0], shape: 'rectangular', widthMm: 300, heightMm: 200 }] }), preset('top-and-front', 'Top inlet + front outlet', { plenumPorts: [port({ id: 'B1', name: 'Ø200 duct connection B1', face: 'top', shape: 'round', diameterMm: 200, projectionMm: 120, role: 'inlet' }), port({ id: 'B2', name: 'Terminal opening B2', face: 'front', shape: 'rectangular', widthMm: 300, heightMm: 200, projectionMm: 40, role: 'outlet' })] })] },
  { id: 'plenum-four-outlet', name: 'Multi-outlet plenum', description: 'Distribution box with one inlet and several attached collars.', group: 'Boxes', category: 'Plenums', family: 'plenum', profilePath: 'Rectangle → 4 × Circle', portCount: 5, tags: ['plenum', 'jakolaatikko', 'four outlet', 'distribution'], partType: 'plenum-box', defaults: { name: '600 × 400 plenum with four Ø160 outlets', presetId: 'four-round', bodyWidthMm: 600, bodyHeightMm: 400, bodyDepthMm: 320, endAWidthMm: 400, endAHeightMm: 250, plenumPorts }, presets: [preset('four-round', 'Four round outlets', { plenumPorts }), preset('two-round', 'Two round outlets', { plenumPorts: [plenumPorts[0], plenumPorts[3]] }), preset('mixed', 'Mixed outlets', { plenumPorts: [plenumPorts[0], { ...plenumPorts[1], shape: 'rectangular', widthMm: 220, heightMm: 140 }] })] },
  { id: 'equipment-adapter', name: 'Equipment adapter', description: 'Connects a rectangular duct to a round equipment spigot, optionally angled.', group: 'Boxes', category: 'Mixed profile', family: 'mixed-loft', profilePath: 'Rectangle → Circle', portCount: 2, tags: ['equipment', 'laite', 'adapter', 'kaulus', 'spigot'], partType: 'rectangular-to-round-transition', defaults: { name: '500 × 300 → Ø250 equipment adapter', presetId: 'straight', endAWidthMm: 500, endAHeightMm: 300, endBDiameterMm: 250, lengthMm: 600, horizontalOffsetMm: 0, verticalOffsetMm: 0 }, presets: [preset('straight', 'Straight spigot', { horizontalOffsetMm: 0, verticalOffsetMm: 0, outletHorizontalAngleDeg: 0 }), preset('angled', 'Angled spigot', { horizontalOffsetMm: 120, verticalOffsetMm: 0, outletHorizontalAngleDeg: 18 })] },
  // --- CONNECTIONS ---------------------------------------------------------
  { id: 'round-saddle', name: 'Round saddle on rectangular body', description: 'Round branch collar taken off a rectangular host duct.', group: 'Connections', category: 'Branches', family: 'host-branch', profilePath: 'Duct + round branch', portCount: 3, tags: ['saddle', 'satula', 'branch', 'haara', 'takeoff', 'lähtö', 'round', 'pyöreä'], partType: 'plenum-box', defaults: { name: 'Ø200 top saddle on 500 × 300 duct', presetId: 'top-saddle', bodyWidthMm: 500, bodyHeightMm: 300, bodyDepthMm: 700, endAWidthMm: 500, endAHeightMm: 300, plenumPorts: saddlePorts }, presets: [preset('top-saddle', 'Round saddle on top', { plenumPorts: saddlePorts }), preset('side-saddle', 'Round saddle on side', { plenumPorts: [saddlePorts[0], { ...saddlePorts[1], face: 'right' }] })] },
  { id: 'rectangular-saddle', name: 'Rectangular saddle on rectangular body', description: 'Rectangular branch collar taken off a rectangular host duct.', group: 'Connections', category: 'Branches', family: 'host-branch', profilePath: 'Duct + rectangular branch', portCount: 3, tags: ['saddle', 'satula', 'branch', 'haara', 'takeoff', 'lähtö', 'rectangular'], partType: 'plenum-box', defaults: { name: '300 × 200 side saddle on 600 × 400 duct', presetId: 'side-saddle', bodyWidthMm: 600, bodyHeightMm: 400, bodyDepthMm: 800, endAWidthMm: 600, endAHeightMm: 400, plenumPorts: rectSaddlePorts }, presets: [preset('side-saddle', 'Saddle on side', { plenumPorts: rectSaddlePorts }), preset('top-saddle', 'Saddle on top', { plenumPorts: [rectSaddlePorts[0], { ...rectSaddlePorts[1], face: 'top' }] }), preset('reduced-branch', 'Reduced branch', { plenumPorts: [rectSaddlePorts[0], { ...rectSaddlePorts[1], widthMm: 200, heightMm: 150 }] })] },
];

export const DEMO_TEMPLATE_IDS: PromotionalTemplateId[] = PROMOTIONAL_TEMPLATES.map((template) => template.id);
export function promotionalTemplateById(id?: string): PromotionalTemplateDefinition | undefined { return PROMOTIONAL_TEMPLATES.find((template) => template.id === id); }
export function promotionalTemplateForPart(part: CustomPart): PromotionalTemplateDefinition | undefined { return promotionalTemplateById(part.templateId); }
export function partForThumbnail(template: PromotionalTemplateDefinition): CustomPart {
  const now = 'thumbnail'; const base = { id: `thumb-${template.id}`, name: template.name, partType: template.partType, endAWidthMm: 500, endAHeightMm: 300, endBWidthMm: 300, endBHeightMm: 200, endADiameterMm: 250, endBDiameterMm: 200, lengthMm: 600, horizontalOffsetMm: 0, verticalOffsetMm: 0, outletHorizontalAngleDeg: 0, outletVerticalAngleDeg: 0, outletRotationDeg: 0, quantity: 1, system: 'Supply air', material: 'Galvanized steel', thicknessMm: .7, notes: '', createdAt: now, updatedAt: now, verificationStatus: 'suggested' as const } as CustomPart;
  return syncCustomPartAssembly({ ...base, ...structuredClone(template.defaults), templateId: template.id, partType: template.partType });
}
export function promotionalThumbnail(template: PromotionalTemplateDefinition): string { return realGeometryThumbnail(partForThumbnail(template)); }
